### PR TITLE
Dimos/new venn plot

### PR DESCRIPTION
**Pull request by dimostzim**
Updated venn plot withou solid colors

### CODE REVIEW

**Comment by evaklimentova** [comment]
The colors look nice, it's definitely better for me now.
One small thing - could you please export the file in SVG so there's a possibility to edit it later eg. in Inkskape?
And could you please add somewhere a note about from which dataset it was created? For example link to a script that produces it or some short description.

**Comment by dimostzim** [comment]
SVGs and finals PNGs are uploaded here: 
https://drive.google.com/drive/u/0/folders/1NEaHSXtVpdlIUXY_3FaesJ4enwsaZ5HB

For the plotting I used the family_counts file already created here:
https://github.com/BioGeMT/miRBench_paper/blob/main/code/plots/Fig2/output/family_counts.tsv

Already documented here:
https://github.com/BioGeMT/miRBench_paper/blob/main/code/plots/Fig2/family_count_README.md

I also added a copy of your note about datasets

**Comment by evaklimentova** [comment]
Thanks for explanation :)

**Review by evaklimentova — APPROVED** [review]

**Comment by katarinagresova** [comment]
Could we add some color markings to the names of datasets? To make it clear which dataset is which color

**Comment by dimostzim** [comment]
> Could we add some color markings to the names of datasets? To make it clear which dataset is which color

Done

**Review by stephaniesamm — APPROVED** [review]

**Pull request merged**
